apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zl7rhw205-python
  janus-idp.io/tekton: zl7rhw205-python
  backstage.io/kubernetes-id: zl7rhw205-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zl7rhw205-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
