apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zl7rhw205-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zl7rhw205-python 
  name: zl7rhw205-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zl7rhw205-python 
